CREATE TABLE tours (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner             VARCHAR(255) NOT NULL,
    name              VARCHAR(255) NOT NULL,
    description       TEXT,
    from_location     VARCHAR(255) NOT NULL,
    to_location       VARCHAR(255) NOT NULL,
    transport_type    VARCHAR(50)  NOT NULL,
    distance          DOUBLE PRECISION,
    estimated_time    BIGINT,
    route_information TEXT,
    image_path        VARCHAR(1024)
);

CREATE TABLE tour_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id        BIGINT           NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    date_time      TIMESTAMP        NOT NULL,
    comment        TEXT,
    difficulty     INTEGER          NOT NULL,
    total_distance DOUBLE PRECISION NOT NULL,
    total_time     BIGINT           NOT NULL,
    rating         INTEGER          NOT NULL
);

CREATE INDEX idx_tours_owner ON tours (owner);
CREATE INDEX idx_tour_logs_tour_id ON tour_logs (tour_id);
