spring.application.name=Tour Planner
spring.datasource.url=jdbc:postgresql://localhost:5432/tourplanner
spring.datasource.username=tourplanner
spring.datasource.password=LVfkSrV5wBDqlpENm4iTCK0RC+Sg7XdG
spring.jpa.show-sql=true

# Authentik OIDC Configuration
spring.security.oauth2.client.registration.authentik.client-id=tour-planner
spring.security.oauth2.client.registration.authentik.client-secret=BmCrVHqfVKrQxwQkTEjMB7HvN6uy4Bto5AnggZNii/c=
spring.security.oauth2.client.registration.authentik.scope=openid,profile,email
spring.security.oauth2.client.registration.authentik.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authentik.redirect-uri={baseUrl}/login/oauth2/code/authentik
spring.security.oauth2.client.provider.authentik.issuer-uri=http://localhost:8000/application/o/tour-planner/